# Лабораторна робота: Pandas + Бази даних (SQL)

Робота з реляційними базами даних через Pandas для Data Engineering.

---
**Рівень:** Junior Data Engineer  
**Що вивчите:** підключення до БД, читання/запис таблиць, SQL-запити, транзакції, оптимізація

In [20]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text, inspect
import warnings
warnings.filterwarnings('ignore')

print(f'Pandas: {pd.__version__}')
print(f'SQLAlchemy: installed')

Pandas: 3.0.3
SQLAlchemy: installed

---
## 1. Підключення до бази даних

**SQLAlchemy** — стандартний спосіб підключення Python до будь-якої реляційної БД.

```
SQLite:   sqlite:///path/to/db.db
PostgreSQL: postgresql://user:pass@host:5432/dbname
MySQL:     mysql+pymysql://user:pass@host:3306/dbname
MSSQL:     mssql+pyodbc://user:pass@host/dbname
```

In [21]:
# SQLite in-memory — ідеально для лабораторних
engine = create_engine('sqlite:///:memory:', echo=False)

# Перевірка підключення
with engine.connect() as conn:
    result = conn.execute(text('SELECT 1 AS test'))
    print('Підключення OK:', result.fetchone()[0])

Підключення OK: 1

In [22]:
# Створимо тестову таблицю
create_sql = text("""
CREATE TABLE employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    department TEXT,
    salary REAL,
    hire_date TEXT,
    is_active INTEGER DEFAULT 1
)
""")

with engine.begin() as conn:
    conn.execute(create_sql)
    conn.execute(text("INSERT INTO employees VALUES (1, 'Alice', 'IT', 70000, '2022-01-15', 1)"))
    conn.execute(text("INSERT INTO employees VALUES (2, 'Bob', 'HR', 50000, '2023-03-20', 1)"))
    conn.execute(text("INSERT INTO employees VALUES (3, 'Charlie', 'IT', 80000, '2021-06-10', 1)"))
    conn.execute(text("INSERT INTO employees VALUES (4, 'Diana', 'Finance', 55000, '2024-02-01', 0)"))
    conn.execute(text("INSERT INTO employees VALUES (5, 'Eve', 'HR', 65000, '2023-09-05', 1)"))

print('Таблиця employees створена та заповнена')

Таблиця employees створена та заповнена

---
## 2. Читання даних: `pd.read_sql()`

Три способи прочитати дані з БД в DataFrame.

In [23]:
# Спосіб 1: read_sql(sql, engine) — SQL-запит
df = pd.read_sql('SELECT * FROM employees WHERE salary > 55000', engine)
print('Спосіб 1 — read_sql із запитом:')
display(df)

Спосіб 1 — read_sql із запитом:

   emp_id     name department   salary   hire_date  is_active
0       1    Alice         IT  70000.0  2022-01-15          1
1       3  Charlie         IT  80000.0  2021-06-10          1
2       5      Eve         HR  65000.0  2023-09-05          1

In [24]:
# Спосіб 2: read_sql_query(sql, engine) — явно SQL-запит
df = pd.read_sql_query('SELECT department, COUNT(*) AS cnt, ROUND(AVG(salary), 0) AS avg_sal FROM employees GROUP BY department', engine)
print('Спосіб 2 — read_sql_query:')
display(df)

Спосіб 2 — read_sql_query:

  department  cnt  avg_sal
0    Finance    1  55000.0
1         HR    2  57500.0
2         IT    2  75000.0

In [25]:
# Спосіб 3: read_sql_table(table_name, engine) — вся таблиця (тільки SQLAlchemy)
try:
    df = pd.read_sql_table('employees', engine)
    print('Спосіб 3 — read_sql_table:')
    display(df)
except Exception as e:
    print(f'read_sql_table вимагає наявності таблиці в metadata: {e}')

Спосіб 3 — read_sql_table:

   emp_id     name department   salary   hire_date  is_active
0       1    Alice         IT  70000.0  2022-01-15          1
1       2      Bob         HR  50000.0  2023-03-20          1
2       3  Charlie         IT  80000.0  2021-06-10          1
3       4    Diana    Finance  55000.0  2024-02-01          0
4       5      Eve         HR  65000.0  2023-09-05          1

In [26]:
# Параметризовані запити (SQL injection protection)
min_salary = 60000
dept = 'IT'

# Спосіб A: f-строками (НЕБЕЗПЕЧНО!)
# df_bad = pd.read_sql(f"SELECT * FROM employees WHERE salary > {min_salary}", engine)  # SQL injection

# Спосіб B: params як словник ✅
df_safe = pd.read_sql(
    'SELECT * FROM employees WHERE salary > :min_sal AND department = :dept',
    engine,
    params={'min_sal': min_salary, 'dept': dept}
)
print('Параметризований запит:')
display(df_safe)

Параметризований запит:

   emp_id     name department   salary   hire_date  is_active
0       1    Alice         IT  70000.0  2022-01-15          1
1       3  Charlie         IT  80000.0  2021-06-10          1

In [27]:
# Читання з індексом
df_idx = pd.read_sql('SELECT * FROM employees', engine, index_col='emp_id')
print('З індексом на emp_id:')
display(df_idx)

З індексом на emp_id:

           name department   salary   hire_date  is_active
emp_id
1         Alice         IT  70000.0  2022-01-15          1
2           Bob         HR  50000.0  2023-03-20          1
3       Charlie         IT  80000.0  2021-06-10          1
4         Diana    Finance  55000.0  2024-02-01          0
5           Eve         HR  65000.0  2023-09-05          1

---
## 3. Запис даних: `df.to_sql()`

In [28]:
# Створимо DataFrame для запису
new_employees = pd.DataFrame({
    'emp_id': [6, 7, 8],
    'name': ['Frank', 'Grace', 'Hank'],
    'department': ['Marketing', 'IT', 'Finance'],
    'salary': [60000, 75000, 62000],
    'hire_date': ['2024-06-01', '2024-07-15', '2024-08-20'],
    'is_active': [1, 1, 1]
})

# Запис у БД
new_employees.to_sql('employees', engine, if_exists='append', index=False)
print(f'Додано {len(new_employees)} записів')

# Перевірка
df_check = pd.read_sql('SELECT * FROM employees', engine)
display(df_check)

Додано 3 записів

   emp_id     name department   salary   hire_date  is_active
0       1    Alice         IT  70000.0  2022-01-15          1
1       2      Bob         HR  50000.0  2023-03-20          1
2       3  Charlie         IT  80000.0  2021-06-10          1
3       4    Diana    Finance  55000.0  2024-02-01          0
4       5      Eve         HR  65000.0  2023-09-05          1
5       6    Frank  Marketing  60000.0  2024-06-01          1
6       7    Grace         IT  75000.0  2024-07-15          1
7       8     Hank    Finance  62000.0  2024-08-20          1

In [29]:
# Режими if_exists:
# 'append' — додати до існуючої таблиці
# 'replace' — видалити і створити заново
# 'fail' — помилка, якщо таблиця існує

# Запис з різними типами даних
# df.to_sql('table', engine, dtype={'col': sqlalchemy.types.VARCHAR(100)})  # явний тип

# Запис з chunksize (для великих даних)
# df.to_sql('table', engine, chunksize=10000)

In [30]:
# Перезапис таблиці зі створенням схеми
# Записуємо тільки активних
df_active = pd.read_sql("SELECT * FROM employees WHERE is_active = 1", engine)
df_active.to_sql('active_employees', engine, if_exists='replace', index=False)

df_active_check = pd.read_sql('SELECT * FROM active_employees', engine)
print('Таблиця active_employees:')
display(df_active_check)

Таблиця active_employees:

   emp_id     name department   salary   hire_date  is_active
0       1    Alice         IT  70000.0  2022-01-15          1
1       2      Bob         HR  50000.0  2023-03-20          1
2       3  Charlie         IT  80000.0  2021-06-10          1
3       5      Eve         HR  65000.0  2023-09-05          1
4       6    Frank  Marketing  60000.0  2024-06-01          1
5       7    Grace         IT  75000.0  2024-07-15          1
6       8     Hank    Finance  62000.0  2024-08-20          1

---
## 4. Робота з SQLAlchemy ORM

Для складніших операцій — транзакції, metadata, інспекція.

In [31]:
# Інспекція бази даних
inspector = inspect(engine)

print('=== Таблиці в базі ===')
for table_name in inspector.get_table_names():
    print(f'\nТаблиця: {table_name}')
    for column in inspector.get_columns(table_name):
        print(f'  - {column["name"]}: {column["type"]}')

=== Таблиці в базі ===

Таблиця: active_employees
  - emp_id: BIGINT
  - name: TEXT
  - department: TEXT
  - salary: FLOAT
  - hire_date: TEXT
  - is_active: BIGINT

Таблиця: employees
  - emp_id: INTEGER
  - name: TEXT
  - department: TEXT
  - salary: REAL
  - hire_date: TEXT
  - is_active: INTEGER

In [32]:
# Транзакції — commit тільки при успіху
try:
    with engine.begin() as conn:  # auto-commit або rollback
        conn.execute(text("INSERT INTO employees VALUES (9, 'Ivan', 'IT', 90000, '2024-10-01', 1)"))
        conn.execute(text("INSERT INTO employees VALUES (10, 'John', 'HR', 48000, '2024-10-15', 1)"))
        # Якщо тут помилка — обидва INSERT відкочуються
    print('Транзакція успішна, 2 записи додано')
except Exception as e:
    print(f'Транзакція відкочена: {e}')

Транзакція успішна, 2 записи додано

In [33]:
# Ручне керування транзакцією
conn = engine.connect()
trans = conn.begin()
try:
    conn.execute(text("INSERT INTO employees VALUES (11, 'Kate', 'Marketing', 72000, '2024-11-01', 1)"))
    trans.commit()
    print('Коміт')
except:
    trans.rollback()
    print('Rollback')
finally:
    conn.close()

Коміт

---
## 5. ETL-патерн: Extract з БД → Transform → Load назад

Типовий DE-сценарій: читаємо, трансформуємо, пишемо назад.

In [34]:
# CREATE TABLE departments
with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE departments (
            dept_id INTEGER PRIMARY KEY,
            dept_name TEXT,
            budget REAL
        )
    """))
    conn.execute(text("INSERT INTO departments VALUES (1, 'IT', 500000)"))
    conn.execute(text("INSERT INTO departments VALUES (2, 'HR', 300000)"))
    conn.execute(text("INSERT INTO departments VALUES (3, 'Finance', 400000)"))
    conn.execute(text("INSERT INTO departments VALUES (4, 'Marketing', 350000)"))

print('Таблиця departments створена')

Таблиця departments створена

In [35]:
def etl_department_report(engine) -> pd.DataFrame:
    # Extract
    emp = pd.read_sql('SELECT * FROM employees', engine)
    dept = pd.read_sql('SELECT * FROM departments', engine)

    # Transform
    merged = (
        emp[emp['is_active'] == 1]
        .merge(
            dept,
            left_on='department',
            right_on='dept_name',
            how='left'
        )
    )

    # Перевіримо, чи є відділи без бюджету
    missing = merged[merged['budget'].isna()]

    if not missing.empty:
        print("Увага! Для цих відділів не знайдено бюджет:")
        print(missing['department'].unique())

    report = (
        merged
        .groupby('dept_name', as_index=False)
        .agg(
            emp_count=('emp_id', 'count'),
            avg_salary=('salary', 'mean'),
            total_salary=('salary', 'sum'),
            budget=('budget', 'first')
        )
    )

    # Розрахунок використання бюджету
    report['budget_utilization'] = (
        report['total_salary'] / report['budget']
    )

    report = (
        report
        .round(1)
        .sort_values('avg_salary', ascending=False)
    )

    # Load
    report_simple = report[
        [
            'dept_name',
            'emp_count',
            'avg_salary',
            'total_salary'
        ]
    ].copy()

    report_simple.to_sql(
        'dept_report',
        engine,
        if_exists='replace',
        index=False
    )

    return report_simple


# Виклик функції
result = etl_department_report(engine)

print('=== Department Report ===')
display(result)

=== Department Report ===

   dept_name  emp_count  avg_salary  total_salary
2         IT          4     78750.0      315000.0
3  Marketing          2     66000.0      132000.0
0    Finance          1     62000.0       62000.0
1         HR          3     54333.3      163000.0

---
## 6. Робота з PostgreSQL (якщо доступний)

Для справжнього DE потрібні справжні БД. Приклад підключення.

In [36]:
# ---- PostgreSQL (закоментировано — для локального запуску) ----
# PG_URI = 'postgresql://user:password@localhost:5432/mydb'
# pg_engine = create_engine(PG_URI)
#
# df_pg = pd.read_sql('SELECT * FROM orders LIMIT 100', pg_engine)
#
# df_result.to_sql('analytics_results', pg_engine, if_exists='append', index=False)

print('Для підключення до PostgreSQL:')
print('pip install psycopg2-binary')
print('''
pg_engine = create_engine(
    "postgresql://user:password@host:5432/dbname"
)
df = pd.read_sql('SELECT * FROM table', pg_engine)
''')

Для підключення до PostgreSQL:
pip install psycopg2-binary

pg_engine = create_engine(
    "postgresql://user:password@host:5432/dbname"
)
df = pd.read_sql('SELECT * FROM table', pg_engine)

In [37]:
# ---- MySQL приклад ----
print('Для MySQL:')
print('pip install pymysql')
print('''
mysql_engine = create_engine(
    "mysql+pymysql://user:password@host:3306/dbname"
)
''')

Для MySQL:
pip install pymysql

mysql_engine = create_engine(
    "mysql+pymysql://user:password@host:3306/dbname"
)

In [38]:
# ---- MSSQL (SQL Server) приклад ----
print('Для MSSQL:')
print('pip install pyodbc')
print('''
mssql_engine = create_engine(
    "mssql+pyodbc://user:password@host:1433/dbname?driver=ODBC+Driver+18+for+SQL+Server"
)
''')

Для MSSQL:
pip install pyodbc

mssql_engine = create_engine(
    "mssql+pyodbc://user:password@host:1433/dbname?driver=ODBC+Driver+18+for+SQL+Server"
)

---
## 7. Оптимізація: великі дані та продуктивність

In [39]:
# Створимо велику таблицю для тесту продуктивності
n = 100000
big_data = pd.DataFrame({
    'id': range(n),
    'category': np.random.choice(['A', 'B', 'C', 'D', 'E'], size=n),
    'value': np.random.randn(n),
    'date': pd.date_range('2020-01-01', periods=n, freq='h')[:n]
})

big_data.to_sql('big_table', engine, if_exists='replace', index=False, chunksize=10000)
print(f'Записано {n} рядків у big_table')

Записано 100000 рядків у big_table

In [40]:
# Читання з chunksize — по 20000 рядків
print('Читання big_table частинами:')
total_sum = 0.0
total_rows = 0

for chunk in pd.read_sql('SELECT * FROM big_table', engine, chunksize=20000):
    total_sum += chunk['value'].sum()
    total_rows += len(chunk)
    print(f'  Прочитано частину: {len(chunk)} рядків')

print(f'\nВсього: {total_rows} рядків, сума value: {total_sum:.2f}')

Читання big_table частинами:
  Прочитано частину: 20000 рядків
  Прочитано частину: 20000 рядків
  Прочитано частину: 20000 рядків
  Прочитано частину: 20000 рядків
  Прочитано частину: 20000 рядків

Всього: 100000 рядків, сума value: -187.03

In [41]:
# Читання тільки потрібних колонок (економить пам'ять і час)
df_cols = pd.read_sql('SELECT id, category, value FROM big_table WHERE category = "A"', engine)
print(f'Категорія A: {len(df_cols)} рядків')

# Агрегація на стороні БД (швидше, ніж в Pandas!)
df_agg = pd.read_sql('''
    SELECT category, COUNT(*) AS cnt, AVG(value) AS avg_val, SUM(value) AS sum_val
    FROM big_table
    GROUP BY category
''', engine)
print('\nАгрегація на боці БД:')
display(df_agg.round(3))

Категорія A: 20046 рядків

Агрегація на боці БД:

  category    cnt  avg_val  sum_val
0        A  20046   -0.012 -246.923
1        B  19887    0.004   86.972
2        C  19972   -0.001  -23.548
3        D  20101    0.011  214.372
4        E  19994   -0.011 -217.901

---
## 8. Робота з кількома базами одночасно (Cross-DB ETL)

В реальному DE ви берете дані з однієї БД і пишете в іншу.

In [42]:
# Симуляція cross-DB ETL
source_engine = create_engine('sqlite:///:memory:', echo=False)
target_engine = create_engine('sqlite:///:memory:', echo=False)

# Створимо source
src_df = pd.DataFrame({
    'order_id': range(1, 101),
    'customer': np.random.choice(['Alice', 'Bob', 'Charlie'], 100),
    'amount': np.round(np.random.uniform(10, 500, 100), 2),
    'order_date': pd.date_range('2024-01-01', periods=100, freq='D')
})
src_df.to_sql('orders', source_engine, if_exists='replace', index=False)
print(f'Source: {len(src_df)} orders')

Source: 100 orders

In [43]:
# ETL: Extract з source → Transform → Load в target
def cross_db_etl(src_engine, tgt_engine):
    # Extract
    df = pd.read_sql('SELECT * FROM orders', src_engine)

    # Transform
    df['order_date'] = pd.to_datetime(df['order_date'])
    df['year_month'] = df['order_date'].dt.to_period('M').astype(str)
    df['amount_category'] = pd.cut(df['amount'], bins=[0, 50, 200, 1000], labels=['small', 'medium', 'large'])

    report = df.groupby(['customer', 'year_month', 'amount_category'], as_index=False).agg(
        order_count=('order_id', 'count'),
        total_amount=('amount', 'sum'),
        avg_amount=('amount', 'mean')
    ).round(2)

    # Load
    report.to_sql('order_analytics', tgt_engine, if_exists='replace', index=False)
    return report

result = cross_db_etl(source_engine, target_engine)
print('=== Order Analytics Report ===')
display(result.head(10))
print(f'\nВсього рядків у target: {len(result)}')

=== Order Analytics Report ===

  customer year_month amount_category  order_count  total_amount  avg_amount
0    Alice    2024-01           small            1         11.05       11.05
1    Alice    2024-01          medium            5        700.60      140.12
2    Alice    2024-01           large            7       2165.68      309.38
3    Alice    2024-02           small            1         38.73       38.73
4    Alice    2024-02          medium            1        140.21      140.21
5    Alice    2024-02           large            3       1244.32      414.77
6    Alice    2024-03          medium            4        476.74      119.18
7    Alice    2024-03           large            4       1493.97      373.49
8    Alice    2024-04           small            1         39.32       39.32
9    Alice    2024-04           large            4       1688.09      422.02

Всього рядків у target: 29

---
## 9. Робота з SQL через Pandas + SQLite (файл)

Збережемо базу у файл для постійного використання.

In [44]:
import os
os.makedirs('demo_data', exist_ok=True)

# Створюємо файлову SQLite базу
file_engine = create_engine('sqlite:///demo_data/de_lab.db', echo=False)

# Пишемо дані
df.to_sql('employees_backup', file_engine, if_exists='replace', index=False)

# Читаємо
df_file = pd.read_sql('SELECT * FROM employees_backup', file_engine)
print(f'База demo_data/de_lab.db створена, таблиця employees_backup: {len(df_file)} рядків')
display(df_file.head())

База demo_data/de_lab.db створена, таблиця employees_backup: 5 рядків

   emp_id     name department   salary   hire_date  is_active
0       1    Alice         IT  70000.0  2022-01-15          1
1       2      Bob         HR  50000.0  2023-03-20          1
2       3  Charlie         IT  80000.0  2021-06-10          1
3       4    Diana    Finance  55000.0  2024-02-01          0
4       5      Eve         HR  65000.0  2023-09-05          1

---
## 10. Практичні завдання

1. **Підключіться** до SQLite бази `demo_data/de_lab.db`
2. **Створіть** таблицю `products` (product_id, name, category, price, stock)
3. **Завантажте** 20 продуктів через DataFrame
4. **Знайдіть** категорію з найбільшою середньою ціною
5. **Зробіть** звіт: кількість продуктів, середня ціна, загальний запас по категоріях
6. **Збережіть** звіт у нову таблицю `category_report`
7. (Бонус) **Підключіться** до PostgreSQL/MySQL (якщо є) і прочитайте таблицю

In [45]:
# === Розв'язання ===

# 1-3. Створення таблиці products
products = pd.DataFrame({
    'product_id': range(1, 21),
    'name': [f'Product_{i}' for i in range(1, 21)],
    'category': np.random.choice(['Electronics', 'Clothing', 'Food', 'Books'], 20),
    'price': np.round(np.random.uniform(10, 500, 20), 2),
    'stock': np.random.randint(0, 100, 20)
})

products.to_sql('products', file_engine, if_exists='replace', index=False)
print('Таблиця products створена:')
display(products.head())

Таблиця products створена:

   product_id       name     category   price  stock
0           1  Product_1     Clothing  429.83     54
1           2  Product_2         Food  177.83     17
2           3  Product_3  Electronics  176.03     50
3           4  Product_4        Books   57.26     72
4           5  Product_5     Clothing  444.40     96

In [46]:
# 4-6. Аналіз та звіт
report = pd.read_sql('''
    SELECT 
        category,
        COUNT(*) AS product_count,
        ROUND(AVG(price), 2) AS avg_price,
        ROUND(SUM(price * stock), 2) AS total_stock_value
    FROM products
    GROUP BY category
    ORDER BY avg_price DESC
''', file_engine)

print('=== Category Report ===')
display(report)

report.to_sql('category_report', file_engine, if_exists='replace', index=False)
print('Збережено в category_report')

=== Category Report ===

      category  product_count  avg_price  total_stock_value
0     Clothing              9     341.54          172439.54
1        Books              5     302.33           87856.24
2  Electronics              3     271.99           17995.93
3         Food              3     250.58           35951.49

Збережено в category_report

---
## Висновки

| Операція | Метод Pandas | Коли використовувати |
|----------|-------------|---------------------|
| Читання SQL | `pd.read_sql()` | Будь-який SQL-запит |
| Читання таблиці | `pd.read_sql_table()` | Вся таблиця без SQL |
| Запис | `df.to_sql()` | DataFrame в БД |
| Параметризація | `params={}` | Захист від SQL injection |
| Транзакції | `engine.begin()` | Атомарні операції |
| Chunking | `chunksize=N` | Великі дані |

> **Порада DE**: важкі обчислення (GROUP BY, JOIN) робіть на стороні БД через SQL, а не в Pandas. БД оптимізована для цього. Pandas використовуйте для того, з чим БД не справляється (складна логіка, ML, нестандартні трансформації).